//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.COMP_PRODUCT = new HashSet<COMP_PRODUCT>();
        }
    
        public string PRD_ID { get; set; }
        public string USER_ID { get; set; }
        public string SOFT_CODE { get; set; }
        public string SOFT_NAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PRD_PATH { get; set; }
        public string PRD_NOTE { get; set; }
        public string FACILITIES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMP_PRODUCT> COMP_PRODUCT { get; set; }
    }
}
