//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaadeenSiteEntities : DbContext
    {
        public RaadeenSiteEntities()
            : base("name=RaadeenSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMP_PRODUCT> COMP_PRODUCT { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<SALE_DETAIL> SALE_DETAIL { get; set; }
        public virtual DbSet<SALE_USERS> SALE_USERS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
    }
}
