//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE_USERS()
        {
            this.COMPANies = new HashSet<COMPANY>();
            this.COMPANies1 = new HashSet<COMPANY>();
            this.SALE_DETAIL = new HashSet<SALE_DETAIL>();
        }
    
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string TEL_NO_1 { get; set; }
        public string CELL_PHONE { get; set; }
        public string NOTE { get; set; }
        public string USER_FLAG { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY> COMPANies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY> COMPANies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_DETAIL> SALE_DETAIL { get; set; }
    }
}
