//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_DETAIL
    {
        public decimal DET_ID { get; set; }
        public string DESC1 { get; set; }
        public string F_DATE { get; set; }
        public string COMP_CODE { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string PRD_ID { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public string FOLLOW_DATE { get; set; }
    
        public virtual COMP_PRODUCT COMP_PRODUCT { get; set; }
        public virtual SALE_USERS SALE_USERS { get; set; }
    }
}
